# Generated by Django 4.0.6 on 2022-09-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='mode_preparo',
            new_name='modo_preparo',
        ),
    ]
